### ISSUE TITLE
Page not rendering (2)

### ISSUE THREAD

**Issue by mohdhm** [jmopr/job-hunter#10]
OS: Ubuntu

Seems like  boxboi1471 and I, have a similar problem with a different error message:

After I fill in

     Enter job title or keywords`

     Enter city, state or zip code`

     Pages to inspect (not needed for angel site) > I am using indeed, so i enter "1" to test`

and Click "Find Jobs", No Jobs are displayed. The page refreshes and erases all entered information with no hits.

Started GET "/search?utf8=%E2%9C%93&title=Engineer&location=CA&pages=10&indeed_scraper=1&commit=Find+Jobs" for 127.0.0.1 at 2016-11-19 21:00:26 -0800
Processing by JobsController#search as HTML
  Parameters: {"utf8"=>"✓", "title"=>"Engineer", "location"=>"CA", "pages"=>"10", "indeed_scraper"=>"1", "commit"=>"Find Jobs"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
Running via Spring preloader in process 2763
/var/lib/gems/2.3.0/gems/capybara-2.7.0/lib/capybara/node/finders.rb:44:in `block in find': Unable to find field "q" (Capybara::ElementNotFound)
	from /var/lib/gems/2.3.0/gems/capybara-2.7.0/lib/capybara/node/base.rb:85:in `synchronize'
	from /var/lib/gems/2.3.0/gems/capybara-2.7.0/lib/capybara/node/finders.rb:33:in `find'
	from /var/lib/gems/2.3.0/gems/capybara-2.7.0/lib/capybara/node/actions.rb:59:in `fill_in'
	from /var/lib/gems/2.3.0/gems/capybara-2.7.0/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
	from /var/lib/gems/2.3.0/gems/capybara-2.7.0/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
	from scraper.rb:138:in `perform_search'
	from scraper.rb:33:in `scrape'
	from scraper.rb:145:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/runner.rb:60:in `load'
	from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/shap/Desktop/job-hunter-master/bin/rails:9:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
Redirected to http://localhost:3000/users/jobs
Completed 302 Found in 8221ms (ActiveRecord: 0.2ms)

**Comment by sudhansusingh22** [comment]
@mohdhm Look at the this post : http://stackoverflow.com/questions/41682518/unable-to-find-field-q-capybaraelementnotfound-via-fill-in

**Comment by mohdhm** [comment]
That's my post :)

**Comment by abunsen** [comment]
@mohdhm looks like @moharnab123saikia might have fixed your problem?

**Comment by MoHabib88** [comment]
@abunsen yes it did fix the problem, sorry for not closing this earlier
